name: Bug report
description: Report a reproducible problem with the image or scripts.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug. Please fill out the details
        below so we can reproduce the issue.
  - type: checkboxes
    id: checks
    attributes:
      label: Preconditions
      options:
        - label: I searched existing issues to avoid duplicates.
          required: true
        - label: I am using a supported version (see SECURITY.md).
          required: true
  - type: input
    id: image
    attributes:
      label: Image and tag
      description: e.g. galeriadb/12.1:latest
      placeholder: galeriadb/12.1:latest
    validations:
      required: true
  - type: input
    id: orchestrator
    attributes:
      label: Orchestrator
      description: Docker Compose, Swarm, Kubernetes, or plain Docker
      placeholder: Docker Compose
    validations:
      required: true
  - type: input
    id: host
    attributes:
      label: Host OS and Docker version
      placeholder: Ubuntu 24.04, Docker 26.x
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Include configuration snippets, compose files, or commands.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Paste startup logs or error output.
      render: shell
