name: Feature request
description: Suggest an enhancement or new capability.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the idea! Please provide enough context for us to evaluate
        the request.
  - type: checkboxes
    id: checks
    attributes:
      label: Preconditions
      options:
        - label: I searched existing issues to avoid duplicates.
          required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the change you'd like to see.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative approaches or workarounds?
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Links, screenshots, or other details.
