#!/usr/bin/env bash

require_env GALERIA_PEERS GALERIA_ROOT_PASSWORD GALERIA_BOOTSTRAP_CANDIDATE

: "${GALERIA_CLUSTER_NAME:=galera_cluster}"
: "${GALERIA_DISCOVERY_TIMEOUT:=5}"
: "${GALERIA_DISCOVERY_INTERVAL:=1}"
: "${GALERIA_JOIN_PRIMARY_TIMEOUT:=30}"
: "${GALERIA_MARIADB_LOGS:=off}"

export MYSQL_PWD="${GALERIA_ROOT_PASSWORD}"
