#!/usr/bin/env bash

ROOT_SQL="CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY '${GALERIA_ROOT_PASSWORD}';
GRANT ALL ON *.* TO 'root'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;"
mariadb -u root -e "$ROOT_SQL" 2>/dev/null || true

if [ -n "${GALERIA_HEALTHCHECK_USER:-}" ] && [ -n "${GALERIA_HEALTHCHECK_PASSWORD:-}" ] && [ "${GALERIA_HEALTHCHECK_USER}" != "root" ]; then
  HEALTH_SQL="CREATE USER IF NOT EXISTS '${GALERIA_HEALTHCHECK_USER}'@'%' IDENTIFIED BY '${GALERIA_HEALTHCHECK_PASSWORD}';
ALTER USER '${GALERIA_HEALTHCHECK_USER}'@'%' IDENTIFIED BY '${GALERIA_HEALTHCHECK_PASSWORD}';
GRANT PROCESS ON *.* TO '${GALERIA_HEALTHCHECK_USER}'@'%';
FLUSH PRIVILEGES;"
  mariadb -u root -e "$HEALTH_SQL" 2>/dev/null || true
fi
